#Compare MAPD vs mrpb for 5 kinds of normalizations: ref of 10 tums, ref of 5 norms, ref of 327 norms, flat ref, flat ref with additinonal pca-adjustment
#Created by Rebecka Bergström on 2016-04-14

library(RColorBrewer)

path_CNVkit <- "/home/rebecka.bergstrom/cnvkit/BREASTv6_all/MAPDcomp/"

mrpb_refFlat_nonadj <- read.table(paste(path_CNVkit,"mrpb_refFlat_nonadj.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_refFlat_adj <- read.table(paste(path_CNVkit,"mrpb_refFlat_adj.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_refFlat_func_adj <- read.table(paste(path_CNVkit,"mrpb_refFlat_func_adj.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_ref10tum <- read.table(paste(path_CNVkit,"mrpb_ref10tum.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_ref5norm <- read.table(paste(path_CNVkit,"mrpb_ref5norm.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_ref327norm <- read.table(paste(path_CNVkit,"mrpb_ref327norm.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_wgs <- read.table(paste(path_CNVkit,"mrpb_wgs.txt",sep=""),header=TRUE,as.is=TRUE)

MAPD_refFlat_nonadj <- read.table(paste(path_CNVkit,"MAPD_refFlat_nonadj.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_refFlat_adj <- read.table(paste(path_CNVkit,"MAPD_refFlat_adj.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_refFlat_func_adj <- read.table(paste(path_CNVkit,"MAPD_refFlat_func_adj.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_ref10tum <- read.table(paste(path_CNVkit,"MAPD_ref10tum.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_ref5norm <- read.table(paste(path_CNVkit,"MAPD_ref5norm.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_ref327norm <- read.table(paste(path_CNVkit,"MAPD_ref327norm.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_wgs <- read.table(paste(path_CNVkit,"MAPD_wgs.txt",sep=""),header=TRUE,as.is=TRUE)

setwd(path_CNVkit)
reads=1:3000
mapd<-c()
for (i in 1:3000) mapd[i]=median(abs(diff(log2(rpois(10000,reads[i])/reads[i]))))
filename_MAPD <- "MAPD_comp_refs_with_wgs.jpeg"

#pdf(filename_MAPD,width=20,height=9.8)
jpeg(filename_MAPD,width=9,height=7.5,quality=90,units="in",res=600)
layout(matrix(1:3,1,3,byrow=TRUE))
par(mar=c(5,4.5,4,2)+0.1)
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='targets & antitargets',log="x",ylim=c(0,0.6),xlim=c(20,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
cols <- c("red","blue","green","purple","orange","darkgreen","yellow3")
#cols <- brewer.pal(6,"Set1")
points(as.double(mrpb_ref5norm[,1]),MAPD_ref5norm[,1],col=cols[1],pch=1)
points(as.double(mrpb_ref5norm[,2]),MAPD_ref5norm[,2],col=cols[1],pch=4)
points(as.double(mrpb_ref327norm[,1]),MAPD_ref327norm[,1],col=cols[2],pch=1)
points(as.double(mrpb_ref327norm[,2]),MAPD_ref327norm[,2],col=cols[2],pch=4)
points(as.double(mrpb_ref10tum[,1]),MAPD_ref10tum[,1],col=cols[3],pch=1)
points(as.double(mrpb_ref10tum[,2]),MAPD_ref10tum[,2],col=cols[3],pch=4)
points(as.double(mrpb_refFlat_nonadj[,1]),MAPD_refFlat_nonadj[,1],col=cols[4],pch=1)
points(as.double(mrpb_refFlat_nonadj[,2]),MAPD_refFlat_nonadj[,2],col=cols[4],pch=4)
points(as.double(mrpb_refFlat_adj[,1]),MAPD_refFlat_adj[,1],col=cols[5],pch=1)
points(as.double(mrpb_refFlat_adj[,2]),MAPD_refFlat_adj[,2],col=cols[5],pch=4)
points(as.double(mrpb_refFlat_func_adj[,1]),MAPD_refFlat_func_adj[,1],col=cols[6],pch=1)
points(as.double(mrpb_refFlat_func_adj[,2]),MAPD_refFlat_func_adj[,2],col=cols[6],pch=4)
points(mrpb_wgs[,1],MAPD_wgs[,1],col=cols[7],pch=17)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor + pca clust adj","GC cor + pca funct adj"," ","bin type:", "target", "antitarget"," ","wgs", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,NA,1,1,NA,cols[7],NA,1,1),pch=c(NA,rep(16,6),NA,NA,1,4,NA,17,rep(NA,3)),lty=c(rep(NA,14),1,2))

plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on antitargets',log="x",ylim=c(0,0.5),xlim=c(20,650),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[,2]),MAPD_ref5norm[,2],col=cols[1],pch=4)
points(as.double(mrpb_ref327norm[,2]),MAPD_ref327norm[,2],col=cols[2],pch=4)
points(as.double(mrpb_ref10tum[,2]),MAPD_ref10tum[,2],col=cols[3],pch=4)
points(as.double(mrpb_refFlat_nonadj[,2]),MAPD_refFlat_nonadj[,2],col=cols[4],pch=4)
points(as.double(mrpb_refFlat_adj[,2]),MAPD_refFlat_adj[,2],col=cols[5],pch=4)
points(as.double(mrpb_refFlat_func_adj[,2]),MAPD_refFlat_func_adj[,2],col=cols[6],pch=4)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor + pca clust adj","GC cor + pca funct adj", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),pch=c(NA,rep(4,6),rep(NA,3)),lty=c(rep(NA,8),1,2))

plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on targets',log="x",ylim=c(0,0.25),xlim=c(650,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[,1]),MAPD_ref5norm[,1],col=cols[1],pch=1)
points(as.double(mrpb_ref327norm[,1]),MAPD_ref327norm[,1],col=cols[2],pch=1)
points(as.double(mrpb_ref10tum[,1]),MAPD_ref10tum[,1],col=cols[3],pch=1)
points(as.double(mrpb_refFlat_nonadj[,1]),MAPD_refFlat_nonadj[,1],col=cols[4],pch=1)
points(as.double(mrpb_refFlat_adj[,1]),MAPD_refFlat_adj[,1],col=cols[5],pch=1)
points(as.double(mrpb_refFlat_func_adj[,1]),MAPD_refFlat_func_adj[,1],col=cols[6],pch=1)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor + pca clust adj","GC cor + pca funct adj", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),pch=c(NA,rep(1,6),rep(NA,3)),lty=c(rep(NA,8),1,2))

dev.off()

##

#only one panel with all (targets & antitargets)
filename_MAPD <- "MAPD_comp_refs_with_wgs_1plotAll.jpeg"
jpeg(filename_MAPD,width=9,height=7.5,quality=90,units="in",res=600)
layout(matrix(1,1,1,byrow=TRUE))
par(mar=c(5,4.5,4,2)+0.1)
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='targets & antitargets',log="x",ylim=c(0,0.6),xlim=c(20,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
cols <- c("red","blue","green","purple","orange","darkgreen","yellow3")
#cols <- brewer.pal(6,"Set1")
points(as.double(mrpb_ref5norm[,1]),MAPD_ref5norm[,1],col=cols[1],pch=1)
points(as.double(mrpb_ref5norm[,2]),MAPD_ref5norm[,2],col=cols[1],pch=4)
points(as.double(mrpb_ref327norm[,1]),MAPD_ref327norm[,1],col=cols[2],pch=1)
points(as.double(mrpb_ref327norm[,2]),MAPD_ref327norm[,2],col=cols[2],pch=4)
points(as.double(mrpb_ref10tum[,1]),MAPD_ref10tum[,1],col=cols[3],pch=1)
points(as.double(mrpb_ref10tum[,2]),MAPD_ref10tum[,2],col=cols[3],pch=4)
points(as.double(mrpb_refFlat_nonadj[,1]),MAPD_refFlat_nonadj[,1],col=cols[4],pch=1)
points(as.double(mrpb_refFlat_nonadj[,2]),MAPD_refFlat_nonadj[,2],col=cols[4],pch=4)
points(as.double(mrpb_refFlat_adj[,1]),MAPD_refFlat_adj[,1],col=cols[5],pch=1)
points(as.double(mrpb_refFlat_adj[,2]),MAPD_refFlat_adj[,2],col=cols[5],pch=4)
points(as.double(mrpb_refFlat_func_adj[,1]),MAPD_refFlat_func_adj[,1],col=cols[6],pch=1)
points(as.double(mrpb_refFlat_func_adj[,2]),MAPD_refFlat_func_adj[,2],col=cols[6],pch=4)
points(mrpb_wgs[,1],MAPD_wgs[,1],col=cols[7],pch=17)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor + pca clust adj","GC cor + pca funct adj"," ","bin type:", "target", "antitarget"," ","wgs", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,NA,1,1,NA,cols[7],NA,1,1),pch=c(NA,rep(16,6),NA,NA,1,4,NA,17,rep(NA,3)),lty=c(rep(NA,14),1,2))
dev.off()





##########

assigned_clust <- as.vector(as.matrix(read.table("/home/rebecka.bergstrom/cnvkit/BREASTv6_all/Rplots/smooth/randTestSet/pca/withoutY/assigend_clust_testset.txt",as.is=TRUE)))
assigned_clust[which(MAPD_refFlat_adj[,1] > MAPD_ref327norm[,1])]

#plot for each cluster
setwd(path_CNVkit)
filename_MAPD_clust <- "MAPD_comp_refs_clusters.pdf"
pdf(filename_MAPD_clust,width=20,height=9.8)
layout(matrix(1:8,2,4,byrow = TRUE))
par(mar=c(5,4,4,2)+0.1)
#targets
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, targets, cluster 1',log="x",ylim=c(0,0.25),xlim=c(650,3000))
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[which(assigned_clust==1),1]),MAPD_ref5norm[which(assigned_clust==1),1],col=cols[1],pch=1)
points(as.double(mrpb_ref327norm[which(assigned_clust==1),1]),MAPD_ref327norm[which(assigned_clust==1),1],col=cols[2],pch=1)
points(as.double(mrpb_ref10tum[which(assigned_clust==1),1]),MAPD_ref10tum[which(assigned_clust==1),1],col=cols[3],pch=1)
points(as.double(mrpb_refFlat_nonadj[which(assigned_clust==1),1]),MAPD_refFlat_nonadj[which(assigned_clust==1),1],col=cols[4],pch=1)
points(as.double(mrpb_refFlat_adj[which(assigned_clust==1),1]),MAPD_refFlat_adj[which(assigned_clust==1),1],col=cols[5],pch=1)
points(as.double(mrpb_refFlat_func_adj[which(assigned_clust==1),1]),MAPD_refFlat_func_adj[which(assigned_clust==1),1],col=cols[6],pch=1)
legend_text <- c("5 normals", "327 normals", "10 tumors", "flat ref", "flat ref + pca clust adj", "flat ref + pca funct adj")
legend("topleft",legend_text, col=cols,pch=rep(1,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, targets, cluster 2',log="x",ylim=c(0,0.25),xlim=c(650,3000))
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[which(assigned_clust==2),1]),MAPD_ref5norm[which(assigned_clust==2),1],col=cols[1],pch=1)
points(as.double(mrpb_ref327norm[which(assigned_clust==2),1]),MAPD_ref327norm[which(assigned_clust==2),1],col=cols[2],pch=1)
points(as.double(mrpb_ref10tum[which(assigned_clust==2),1]),MAPD_ref10tum[which(assigned_clust==2),1],col=cols[3],pch=1)
points(as.double(mrpb_refFlat_nonadj[which(assigned_clust==2),1]),MAPD_refFlat_nonadj[which(assigned_clust==2),1],col=cols[4],pch=1)
points(as.double(mrpb_refFlat_adj[which(assigned_clust==2),1]),MAPD_refFlat_adj[which(assigned_clust==2),1],col=cols[5],pch=1)
points(as.double(mrpb_refFlat_func_adj[which(assigned_clust==2),1]),MAPD_refFlat_func_adj[which(assigned_clust==2),1],col=cols[6],pch=1)
legend_text <- c("5 normals", "327 normals", "10 tumors", "flat ref", "flat ref + pca clust adj", "flat ref + pca funct adj")
legend("topleft",legend_text, col=cols,pch=rep(1,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, targets, cluster 3',log="x",ylim=c(0,0.25),xlim=c(650,3000))
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[which(assigned_clust==3),1]),MAPD_ref5norm[which(assigned_clust==3),1],col=cols[1],pch=1)
points(as.double(mrpb_ref327norm[which(assigned_clust==3),1]),MAPD_ref327norm[which(assigned_clust==3),1],col=cols[2],pch=1)
points(as.double(mrpb_ref10tum[which(assigned_clust==3),1]),MAPD_ref10tum[which(assigned_clust==3),1],col=cols[3],pch=1)
points(as.double(mrpb_refFlat_nonadj[which(assigned_clust==3),1]),MAPD_refFlat_nonadj[which(assigned_clust==3),1],col=cols[4],pch=1)
points(as.double(mrpb_refFlat_adj[which(assigned_clust==3),1]),MAPD_refFlat_adj[which(assigned_clust==3),1],col=cols[5],pch=1)
points(as.double(mrpb_refFlat_func_adj[which(assigned_clust==3),1]),MAPD_refFlat_func_adj[which(assigned_clust==3),1],col=cols[6],pch=1)
legend_text <- c("5 normals", "327 normals", "10 tumors", "flat ref", "flat ref + pca clust adj", "flat ref + pca funct adj")
legend("topright",legend_text, col=cols,pch=rep(1,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, targets, cluster 0',log="x",ylim=c(0,0.25),xlim=c(650,3000))
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[which(assigned_clust==0),1]),MAPD_ref5norm[which(assigned_clust==0),1],col=cols[1],pch=1)
points(as.double(mrpb_ref327norm[which(assigned_clust==0),1]),MAPD_ref327norm[which(assigned_clust==0),1],col=cols[2],pch=1)
points(as.double(mrpb_ref10tum[which(assigned_clust==0),1]),MAPD_ref10tum[which(assigned_clust==0),1],col=cols[3],pch=1)
points(as.double(mrpb_refFlat_nonadj[which(assigned_clust==0),1]),MAPD_refFlat_nonadj[which(assigned_clust==0),1],col=cols[4],pch=1)
points(as.double(mrpb_refFlat_adj[which(assigned_clust==0),1]),MAPD_refFlat_adj[which(assigned_clust==0),1],col=cols[5],pch=1)
points(as.double(mrpb_refFlat_func_adj[which(assigned_clust==0),1]),MAPD_refFlat_func_adj[which(assigned_clust==0),1],col=cols[6],pch=1)
legend_text <- c("5 normals", "327 normals", "10 tumors", "flat ref", "flat ref + pca clust adj", "flat ref + pca funct adj")
legend("topright",legend_text, col=cols,pch=rep(1,6))
#antitargets
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, antitargets, cluster 1',log="x",ylim=c(0.1,0.5),xlim=c(20,650))
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[which(assigned_clust==1),2]),MAPD_ref5norm[which(assigned_clust==1),2],col=cols[1],pch=4)
points(as.double(mrpb_ref327norm[which(assigned_clust==1),2]),MAPD_ref327norm[which(assigned_clust==1),2],col=cols[2],pch=4)
points(as.double(mrpb_ref10tum[which(assigned_clust==1),2]),MAPD_ref10tum[which(assigned_clust==1),2],col=cols[3],pch=4)
points(as.double(mrpb_refFlat_nonadj[which(assigned_clust==1),2]),MAPD_refFlat_nonadj[which(assigned_clust==1),2],col=cols[4],pch=4)
points(as.double(mrpb_refFlat_adj[which(assigned_clust==1),2]),MAPD_refFlat_adj[which(assigned_clust==1),2],col=cols[5],pch=4)
points(as.double(mrpb_refFlat_func_adj[which(assigned_clust==1),2]),MAPD_refFlat_func_adj[which(assigned_clust==1),2],col=cols[6],pch=4)
legend_text <- c("5 normals", "327 normals", "10 tumors", "flat ref", "flat ref + pca clust adj", "flat ref + pca funct adj")
legend("topright",legend_text, col=cols,pch=rep(4,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, antitargets, cluster 2',log="x",ylim=c(0.1,0.5),xlim=c(20,650))
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[which(assigned_clust==2),2]),MAPD_ref5norm[which(assigned_clust==2),2],col=cols[1],pch=4)
points(as.double(mrpb_ref327norm[which(assigned_clust==2),2]),MAPD_ref327norm[which(assigned_clust==2),2],col=cols[2],pch=4)
points(as.double(mrpb_ref10tum[which(assigned_clust==2),2]),MAPD_ref10tum[which(assigned_clust==2),2],col=cols[3],pch=4)
points(as.double(mrpb_refFlat_nonadj[which(assigned_clust==2),2]),MAPD_refFlat_nonadj[which(assigned_clust==2),2],col=cols[4],pch=4)
points(as.double(mrpb_refFlat_adj[which(assigned_clust==2),2]),MAPD_refFlat_adj[which(assigned_clust==2),2],col=cols[5],pch=4)
points(as.double(mrpb_refFlat_func_adj[which(assigned_clust==2),2]),MAPD_refFlat_func_adj[which(assigned_clust==2),2],col=cols[6],pch=4)
legend_text <- c("5 normals", "327 normals", "10 tumors", "flat ref", "flat ref + pca clust adj", "flat ref + pca funct adj")
legend("topright",legend_text, col=cols,pch=rep(4,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, antitargets, cluster 3',log="x",ylim=c(0.1,0.5),xlim=c(20,650))
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[which(assigned_clust==3),2]),MAPD_ref5norm[which(assigned_clust==3),2],col=cols[1],pch=4)
points(as.double(mrpb_ref327norm[which(assigned_clust==3),2]),MAPD_ref327norm[which(assigned_clust==3),2],col=cols[2],pch=4)
points(as.double(mrpb_ref10tum[which(assigned_clust==3),2]),MAPD_ref10tum[which(assigned_clust==3),2],col=cols[3],pch=4)
points(as.double(mrpb_refFlat_nonadj[which(assigned_clust==3),2]),MAPD_refFlat_nonadj[which(assigned_clust==3),2],col=cols[4],pch=4)
points(as.double(mrpb_refFlat_adj[which(assigned_clust==3),2]),MAPD_refFlat_adj[which(assigned_clust==3),2],col=cols[5],pch=4)
points(as.double(mrpb_refFlat_func_adj[which(assigned_clust==3),2]),MAPD_refFlat_func_adj[which(assigned_clust==3),2],col=cols[6],pch=4)
legend_text <- c("5 normals", "327 normals", "10 tumors", "flat ref", "flat ref + pca clust adj", "flat ref + pca funct adj")
legend("topright",legend_text, col=cols,pch=rep(4,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, antitargets, cluster 0',log="x",ylim=c(0.1,0.5),xlim=c(20,650))
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[which(assigned_clust==0),2]),MAPD_ref5norm[which(assigned_clust==0),2],col=cols[1],pch=4)
points(as.double(mrpb_ref327norm[which(assigned_clust==0),2]),MAPD_ref327norm[which(assigned_clust==0),2],col=cols[2],pch=4)
points(as.double(mrpb_ref10tum[which(assigned_clust==0),2]),MAPD_ref10tum[which(assigned_clust==0),2],col=cols[3],pch=4)
points(as.double(mrpb_refFlat_nonadj[which(assigned_clust==0),2]),MAPD_refFlat_nonadj[which(assigned_clust==0),2],col=cols[4],pch=4)
points(as.double(mrpb_refFlat_adj[which(assigned_clust==0),2]),MAPD_refFlat_adj[which(assigned_clust==0),2],col=cols[5],pch=4)
points(as.double(mrpb_refFlat_func_adj[which(assigned_clust==0),2]),MAPD_refFlat_func_adj[which(assigned_clust==0),2],col=cols[6],pch=4)
legend_text <- c("5 normals", "327 normals", "10 tumors", "flat ref", "flat ref + pca clust adj", "flat ref + pca funct adj")
legend("topright",legend_text, col=cols,pch=rep(4,6))
dev.off()
