#Compare MAPD vs mrpb for 5 kinds of normalizations: ref of 10 tums, ref of 5 norms, ref of 327 norms, flat ref, flat ref with additinonal pca-adjustment
#Created by Rebecka Bergström on 2016-04-14

library(RColorBrewer)

path_CNVkit <- "/home/rebecka.bergstrom/cnvkit/BREASTv6_all/MAPDcomp/"

mrpb_refFlat_nonadj <- read.table(paste(path_CNVkit,"mrpb_refFlat_nonadj.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_refFlat_adj <- read.table(paste(path_CNVkit,"mrpb_refFlat_adj.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_refFlat_func_adj <- read.table(paste(path_CNVkit,"mrpb_refFlat_func_adj.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_ref10tum <- read.table(paste(path_CNVkit,"mrpb_ref10tum.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_ref5norm <- read.table(paste(path_CNVkit,"mrpb_ref5norm.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_ref327norm <- read.table(paste(path_CNVkit,"mrpb_ref327norm.txt",sep=""),header=TRUE,as.is=TRUE)
mrpb_wgs <- read.table(paste(path_CNVkit,"mrpb_wgs.txt",sep=""),header=TRUE,as.is=TRUE)

MAPD_refFlat_nonadj <- read.table(paste(path_CNVkit,"MAPD_refFlat_nonadj.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_refFlat_adj <- read.table(paste(path_CNVkit,"MAPD_refFlat_adj.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_refFlat_func_adj <- read.table(paste(path_CNVkit,"MAPD_refFlat_func_adj.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_ref10tum <- read.table(paste(path_CNVkit,"MAPD_ref10tum.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_ref5norm <- read.table(paste(path_CNVkit,"MAPD_ref5norm.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_ref327norm <- read.table(paste(path_CNVkit,"MAPD_ref327norm.txt",sep=""),header=TRUE,as.is=TRUE)
MAPD_wgs <- read.table(paste(path_CNVkit,"MAPD_wgs.txt",sep=""),header=TRUE,as.is=TRUE)

#order due to mrpb
oT_flat <- order(mrpb_refFlat_nonadj[,1])
oT_10tum <- order(mrpb_ref10tum[,1])
oT_5norm <- order(mrpb_ref5norm[,1])
oT_327norm <- order(mrpb_ref327norm[,1])
oAT_flat <- order(mrpb_refFlat_nonadj[,2])
oAT_10tum <- order(mrpb_ref10tum[,2])
oAT_5norm <- order(mrpb_ref5norm[,2])
oAT_327norm <- order(mrpb_ref327norm[,2])
o_wgs <- order(mrpb_wgs)

reads=1:3000
mapd<-c()
for (i in 1:3000) mapd[i]=median(abs(diff(log2(rpois(10000,reads[i])/reads[i]))))
setwd(path_CNVkit)
filename_MAPD <- "MAPD_comp_refs_with_wgs_lines.jpeg"
#pdf(filename_MAPD,width=20,height=9.8)
jpeg(filename_MAPD,width=9,height=7.5,quality=90,units="in",res=600)
layout(matrix(1:3,1,3,byrow=TRUE))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='targets & antitargets',log="x",ylim=c(0,0.6),xlim=c(20,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
cols <- c("red","blue","green","purple","orange","darkgreen","yellow3")
#cols <- brewer.pal(6,"Set1")
points(as.double(mrpb_ref5norm[,1])[oT_5norm],MAPD_ref5norm[,1][oT_5norm],col=cols[1],lty=1,type="l",lwd=2)
points(as.double(mrpb_ref5norm[,2])[oAT_5norm],MAPD_ref5norm[,2][oAT_5norm],col=cols[1],lty=3,type="l",lwd=2)
points(as.double(mrpb_ref327norm[,1])[oT_327norm],MAPD_ref327norm[,1][oT_327norm],col=cols[2],lty=1,type="l",lwd=2)
points(as.double(mrpb_ref327norm[,2])[oAT_327norm],MAPD_ref327norm[,2][oAT_327norm],col=cols[2],lty=3,type="l",lwd=2)
points(as.double(mrpb_ref10tum[,1])[oT_10tum],MAPD_ref10tum[,1][oT_10tum],col=cols[3],lty=1,type="l",lwd=2)
points(as.double(mrpb_ref10tum[,2])[oAT_10tum],MAPD_ref10tum[,2][oAT_10tum],col=cols[3],lty=3,type="l",lwd=2)
points(as.double(mrpb_refFlat_nonadj[,1])[oT_flat],MAPD_refFlat_nonadj[,1][oT_flat],col=cols[4],lty=1,type="l",lwd=2)
points(as.double(mrpb_refFlat_nonadj[,2])[oAT_flat],MAPD_refFlat_nonadj[,2][oAT_flat],col=cols[4],lty=3,type="l",lwd=2)
points(as.double(mrpb_refFlat_adj[,1])[oT_flat],MAPD_refFlat_adj[,1][oT_flat],col=cols[5],lty=1,type="l",lwd=2)
points(as.double(mrpb_refFlat_adj[,2])[oAT_flat],MAPD_refFlat_adj[,2][oAT_flat],col=cols[5],lty=3,type="l",lwd=2)
points(as.double(mrpb_refFlat_func_adj[,1])[oT_flat],MAPD_refFlat_func_adj[,1][oT_flat],col=cols[6],lty=1,type="l",lwd=2)
points(as.double(mrpb_refFlat_func_adj[,2])[oAT_flat],MAPD_refFlat_func_adj[,2][oAT_flat],col=cols[6],lty=3,type="l",lwd=2)
points(mrpb_wgs[o_wgs,1],MAPD_wgs[o_wgs,1],col=cols[7],lty=6,type="l",lwd=2.5)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor + pca clust adj","GC cor + pca funct adj"," ","bin type:", "target", "antitarget"," ","wgs", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,NA,1,1,NA,cols[7],NA,1,1),pch=c(NA,rep(16,6),rep(NA,9)),lty=c(rep(NA,9),1,3,NA,6,NA,1,2),lwd=c(rep(NA,9),2,2,NA,2.5,NA,1,1))

plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on antitargets',log="x",ylim=c(0,0.5),xlim=c(20,650),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[,2])[oAT_5norm],MAPD_ref5norm[,2][oAT_5norm],col=cols[1],lty=3,type="l",lwd=2)
points(as.double(mrpb_ref327norm[,2])[oAT_327norm],MAPD_ref327norm[,2][oAT_327norm],col=cols[2],lty=3,type="l",lwd=2)
points(as.double(mrpb_ref10tum[,2])[oAT_10tum],MAPD_ref10tum[,2][oAT_10tum],col=cols[3],lty=3,type="l",lwd=2)
points(as.double(mrpb_refFlat_nonadj[,2])[oAT_flat],MAPD_refFlat_nonadj[,2][oAT_flat],col=cols[4],lty=3,type="l",lwd=2)
points(as.double(mrpb_refFlat_adj[,2])[oAT_flat],MAPD_refFlat_adj[,2][oAT_flat],col=cols[5],lty=3,type="l",lwd=2)
points(as.double(mrpb_refFlat_func_adj[,2])[oAT_flat],MAPD_refFlat_func_adj[,2][oAT_flat],col=cols[6],lty=3,type="l",lwd=2)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor + pca clust adj","GC cor + pca funct adj", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),lty=c(NA,rep(3,6),NA,1,2),lwd=c(NA,rep(2,6),NA,1,1))

plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on targets',log="x",ylim=c(0,0.25),xlim=c(650,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
points(as.double(mrpb_ref5norm[,1])[oT_5norm],MAPD_ref5norm[,1][oT_5norm],col=cols[1],lty=1,type="l",lwd=2)
points(as.double(mrpb_ref327norm[,1])[oT_327norm],MAPD_ref327norm[,1][oT_327norm],col=cols[2],lty=1,type="l",lwd=2)
points(as.double(mrpb_ref10tum[,1])[oT_10tum],MAPD_ref10tum[,1][oT_10tum],col=cols[3],lty=1,type="l",lwd=2)
points(as.double(mrpb_refFlat_nonadj[,1])[oT_flat],MAPD_refFlat_nonadj[,1][oT_flat],col=cols[4],lty=1,type="l",lwd=2)
points(as.double(mrpb_refFlat_adj[,1])[oT_flat],MAPD_refFlat_adj[,1][oT_flat],col=cols[5],lty=1,type="l",lwd=2)
points(as.double(mrpb_refFlat_func_adj[,1])[oT_flat],MAPD_refFlat_func_adj[,1][oT_flat],col=cols[6],lty=1,type="l",lwd=2)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor + pca clust adj","GC cor + pca funct adj", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),lty=c(NA,rep(1,6),NA,1,2),lwd=c(NA,rep(2,6),NA,1,1))

dev.off()

##########

#Use lowess to smooth the lines
setwd(path_CNVkit)
filename_MAPD <- "MAPD_comp_refs_with_wgs_smooth_lines.jpeg"
#pdf(filename_MAPD,width=20,height=9.8)
jpeg(filename_MAPD,width=9,height=7.5,quality=90,units="in",res=600)
layout(matrix(1:3,1,3,byrow=TRUE))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='targets & antitargets',log="x",ylim=c(0,0.6),xlim=c(20,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
cols <- c("red","blue","green","purple","orange","darkgreen","yellow3")
#cols <- brewer.pal(6,"Set1")
lines(lowess(as.double(mrpb_ref5norm[,1])[oT_5norm],MAPD_ref5norm[,1][oT_5norm],f=1/4),col=cols[1],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref5norm[,2])[oAT_5norm],MAPD_ref5norm[,2][oAT_5norm],f=1/4),col=cols[1],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,1])[oT_327norm],MAPD_ref327norm[,1][oT_327norm],f=1/4),col=cols[2],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,2])[oAT_327norm],MAPD_ref327norm[,2][oAT_327norm],f=1/4),col=cols[2],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,1])[oT_10tum],MAPD_ref10tum[,1][oT_10tum],f=1/4),col=cols[3],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,2])[oAT_10tum],MAPD_ref10tum[,2][oAT_10tum],f=1/4),col=cols[3],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,1])[oT_flat],MAPD_refFlat_nonadj[,1][oT_flat],f=1/4),col=cols[4],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,2])[oAT_flat],MAPD_refFlat_nonadj[,2][oAT_flat],f=1/4),col=cols[4],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,1])[oT_flat],MAPD_refFlat_adj[,1][oT_flat],f=1/4),col=cols[5],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,2])[oAT_flat],MAPD_refFlat_adj[,2][oAT_flat],f=1/4),col=cols[5],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,1])[oT_flat],MAPD_refFlat_func_adj[,1][oT_flat],f=1/4),col=cols[6],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,2])[oAT_flat],MAPD_refFlat_func_adj[,2][oAT_flat],f=1/4),col=cols[6],lty=3,type="l",lwd=2)
lines(lowess(mrpb_wgs[o_wgs,1],MAPD_wgs[o_wgs,1],f=1/4),col=cols[7],lty=6,type="l",lwd=2.5)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "PCA cluster cor","PCA function cor"," ","bin type:", "target", "antitarget"," ","wgs", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,NA,80,80,NA,cols[7],NA,1,1),pch=c(NA,rep(16,6),rep(NA,9)),lty=c(rep(NA,9),1,3,NA,6,NA,1,2),lwd=c(rep(NA,9),2,2,NA,2.5,NA,1,1))

plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on antitargets',log="x",ylim=c(0,0.5),xlim=c(20,650),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(lowess(as.double(mrpb_ref5norm[,2])[oAT_5norm],MAPD_ref5norm[,2][oAT_5norm],f=1/4),col=cols[1],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,2])[oAT_327norm],MAPD_ref327norm[,2][oAT_327norm],f=1/4),col=cols[2],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,2])[oAT_10tum],MAPD_ref10tum[,2][oAT_10tum],f=1/4),col=cols[3],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,2])[oAT_flat],MAPD_refFlat_nonadj[,2][oAT_flat],f=1/4),col=cols[4],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,2])[oAT_flat],MAPD_refFlat_adj[,2][oAT_flat],f=1/4),col=cols[5],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,2])[oAT_flat],MAPD_refFlat_func_adj[,2][oAT_flat],f=1/4),col=cols[6],lty=3,type="l",lwd=2)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "PCA cluster cor","PCA function cor", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),lty=c(NA,rep(3,6),NA,1,2),lwd=c(NA,rep(2,6),NA,1,1))

plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on targets',log="x",ylim=c(0,0.25),xlim=c(650,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(lowess(as.double(mrpb_ref5norm[,1])[oT_5norm],MAPD_ref5norm[,1][oT_5norm],f=1/4),col=cols[1],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,1])[oT_327norm],MAPD_ref327norm[,1][oT_327norm],f=1/4),col=cols[2],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,1])[oT_10tum],MAPD_ref10tum[,1][oT_10tum],f=1/4),col=cols[3],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,1])[oT_flat],MAPD_refFlat_nonadj[,1][oT_flat],f=1/4),col=cols[4],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,1])[oT_flat],MAPD_refFlat_adj[,1][oT_flat],f=1/4),col=cols[5],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,1])[oT_flat],MAPD_refFlat_func_adj[,1][oT_flat],f=1/4),col=cols[6],lty=1,type="l",lwd=2)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "PCA cluster cor","PCA function cor", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),lty=c(NA,rep(1,6),NA,1,2),lwd=c(NA,rep(2,6),NA,1,1))
dev.off()

#wide with LOWESS
setwd(path_CNVkit)
filename_MAPD_wide <- "MAPD_comp_refs_with_wgs_smooth_lines_wide.jpeg"
#pdf(filename_MAPD,width=20,height=9.8)
jpeg(filename_MAPD_wide,width=12,height=7.5,quality=90,units="in",res=1200)
layout(matrix(1:3,1,3,byrow=TRUE))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='targets & antitargets',log="x",ylim=c(0,0.6),xlim=c(20,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
cols <- c("red","blue","green","purple","orange","darkgreen","yellow3")
#cols <- brewer.pal(6,"Set1")
lines(lowess(as.double(mrpb_ref5norm[,1])[oT_5norm],MAPD_ref5norm[,1][oT_5norm],f=1/4),col=cols[1],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref5norm[,2])[oAT_5norm],MAPD_ref5norm[,2][oAT_5norm],f=1/4),col=cols[1],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,1])[oT_327norm],MAPD_ref327norm[,1][oT_327norm],f=1/4),col=cols[2],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,2])[oAT_327norm],MAPD_ref327norm[,2][oAT_327norm],f=1/4),col=cols[2],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,1])[oT_10tum],MAPD_ref10tum[,1][oT_10tum],f=1/4),col=cols[3],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,2])[oAT_10tum],MAPD_ref10tum[,2][oAT_10tum],f=1/4),col=cols[3],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,1])[oT_flat],MAPD_refFlat_nonadj[,1][oT_flat],f=1/4),col=cols[4],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,2])[oAT_flat],MAPD_refFlat_nonadj[,2][oAT_flat],f=1/4),col=cols[4],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,1])[oT_flat],MAPD_refFlat_adj[,1][oT_flat],f=1/4),col=cols[5],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,2])[oAT_flat],MAPD_refFlat_adj[,2][oAT_flat],f=1/4),col=cols[5],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,1])[oT_flat],MAPD_refFlat_func_adj[,1][oT_flat],f=1/4),col=cols[6],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,2])[oAT_flat],MAPD_refFlat_func_adj[,2][oAT_flat],f=1/4),col=cols[6],lty=3,type="l",lwd=2)
lines(lowess(mrpb_wgs[o_wgs,1],MAPD_wgs[o_wgs,1],f=1/4),col=cols[7],lty=6,type="l",lwd=2.5)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "PCA cluster cor","PCA function cor"," ","bin type:", "target", "antitarget"," ","wgs", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,NA,80,80,NA,cols[7],NA,1,1),pch=c(NA,rep(16,6),rep(NA,9)),lty=c(rep(NA,9),1,3,NA,6,NA,1,2),lwd=c(rep(NA,9),2,2,NA,2.5,NA,1,1))

plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on antitargets',log="x",ylim=c(0,0.5),xlim=c(20,650),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(lowess(as.double(mrpb_ref5norm[,2])[oAT_5norm],MAPD_ref5norm[,2][oAT_5norm],f=1/4),col=cols[1],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,2])[oAT_327norm],MAPD_ref327norm[,2][oAT_327norm],f=1/4),col=cols[2],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,2])[oAT_10tum],MAPD_ref10tum[,2][oAT_10tum],f=1/4),col=cols[3],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,2])[oAT_flat],MAPD_refFlat_nonadj[,2][oAT_flat],f=1/4),col=cols[4],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,2])[oAT_flat],MAPD_refFlat_adj[,2][oAT_flat],f=1/4),col=cols[5],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,2])[oAT_flat],MAPD_refFlat_func_adj[,2][oAT_flat],f=1/4),col=cols[6],lty=3,type="l",lwd=2)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "PCA cluster cor","PCA function cor", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),lty=c(NA,rep(3,6),NA,1,2),lwd=c(NA,rep(2,6),NA,1,1))

plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on targets',log="x",ylim=c(0,0.25),xlim=c(650,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(lowess(as.double(mrpb_ref5norm[,1])[oT_5norm],MAPD_ref5norm[,1][oT_5norm],f=1/4),col=cols[1],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,1])[oT_327norm],MAPD_ref327norm[,1][oT_327norm],f=1/4),col=cols[2],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,1])[oT_10tum],MAPD_ref10tum[,1][oT_10tum],f=1/4),col=cols[3],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,1])[oT_flat],MAPD_refFlat_nonadj[,1][oT_flat],f=1/4),col=cols[4],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,1])[oT_flat],MAPD_refFlat_adj[,1][oT_flat],f=1/4),col=cols[5],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,1])[oT_flat],MAPD_refFlat_func_adj[,1][oT_flat],f=1/4),col=cols[6],lty=1,type="l",lwd=2)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "PCA cluster cor","PCA function cor", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),lty=c(NA,rep(1,6),NA,1,2),lwd=c(NA,rep(2,6),NA,1,1))
dev.off()


#Only one plot (targets&antitargets) with LOWESS
filename_MAPD <- "MAPD_comp_refs_with_wgs_smooth_lines_1plotAll.jpeg"
#pdf(filename_MAPD,width=20,height=9.8)
jpeg(filename_MAPD,width=9,height=7.5,quality=90,units="in",res=900)
layout(matrix(1,1,1,byrow=TRUE))
par(mar=c(5,4.3,4,2)+0.1)
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='targets & antitargets',log="x",ylim=c(0,0.6),xlim=c(20,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
cols <- c("red","blue","green","purple","orange","darkgreen","yellow3")
#cols <- brewer.pal(6,"Set1")
lines(lowess(as.double(mrpb_ref5norm[,1])[oT_5norm],MAPD_ref5norm[,1][oT_5norm],f=1/4),col=cols[1],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref5norm[,2])[oAT_5norm],MAPD_ref5norm[,2][oAT_5norm],f=1/4),col=cols[1],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,1])[oT_327norm],MAPD_ref327norm[,1][oT_327norm],f=1/4),col=cols[2],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,2])[oAT_327norm],MAPD_ref327norm[,2][oAT_327norm],f=1/4),col=cols[2],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,1])[oT_10tum],MAPD_ref10tum[,1][oT_10tum],f=1/4),col=cols[3],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,2])[oAT_10tum],MAPD_ref10tum[,2][oAT_10tum],f=1/4),col=cols[3],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,1])[oT_flat],MAPD_refFlat_nonadj[,1][oT_flat],f=1/4),col=cols[4],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,2])[oAT_flat],MAPD_refFlat_nonadj[,2][oAT_flat],f=1/4),col=cols[4],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,1])[oT_flat],MAPD_refFlat_adj[,1][oT_flat],f=1/4),col=cols[5],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,2])[oAT_flat],MAPD_refFlat_adj[,2][oAT_flat],f=1/4),col=cols[5],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,1])[oT_flat],MAPD_refFlat_func_adj[,1][oT_flat],f=1/4),col=cols[6],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,2])[oAT_flat],MAPD_refFlat_func_adj[,2][oAT_flat],f=1/4),col=cols[6],lty=3,type="l",lwd=2)
lines(lowess(mrpb_wgs[o_wgs,1],MAPD_wgs[o_wgs,1],f=1/4),col=cols[7],lty=6,type="l",lwd=2.5)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "PCA cluster cor","PCA function cor"," ","bin type:", "target", "antitarget"," ","wgs", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,NA,1,1,NA,cols[7],NA,1,1),pch=c(NA,rep(16,6),rep(NA,9)),lty=c(rep(NA,9),1,3,NA,6,NA,1,2),lwd=c(rep(NA,9),2,2,NA,2.5,NA,1,1))
dev.off()

#Only one plot, antitargets, with LOWESS
filename_MAPD <- "MAPD_comp_refs_with_wgs_smooth_lines_1plotAntitarg.jpeg"
#pdf(filename_MAPD,width=20,height=9.8)
jpeg(filename_MAPD,width=9,height=7.5,quality=90,units="in",res=900)
layout(matrix(1,1,1,byrow=TRUE))
par(mar=c(5,4.3,4,2)+0.1)
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on antitargets',log="x",ylim=c(0,0.5),xlim=c(20,650),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(lowess(as.double(mrpb_ref5norm[,2])[oAT_5norm],MAPD_ref5norm[,2][oAT_5norm],f=1/4),col=cols[1],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,2])[oAT_327norm],MAPD_ref327norm[,2][oAT_327norm],f=1/4),col=cols[2],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,2])[oAT_10tum],MAPD_ref10tum[,2][oAT_10tum],f=1/4),col=cols[3],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,2])[oAT_flat],MAPD_refFlat_nonadj[,2][oAT_flat],f=1/4),col=cols[4],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,2])[oAT_flat],MAPD_refFlat_adj[,2][oAT_flat],f=1/4),col=cols[5],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,2])[oAT_flat],MAPD_refFlat_func_adj[,2][oAT_flat],f=1/4),col=cols[6],lty=3,type="l",lwd=2)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "PCA cluster cor","PCA function cor", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),lty=c(NA,rep(3,6),NA,1,2),lwd=c(NA,rep(2,6),NA,1,1))
dev.off()

#Only one plot, targets, with LOWESS
filename_MAPD <- "MAPD_comp_refs_with_wgs_smooth_lines_1plotTarg.jpeg"
#pdf(filename_MAPD,width=20,height=9.8)
jpeg(filename_MAPD,width=9,height=7.5,quality=90,units="in",res=900)
layout(matrix(1,1,1,byrow=TRUE))
par(mar=c(5,4.3,4,2)+0.1)
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on targets',log="x",ylim=c(0,0.25),xlim=c(650,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(lowess(as.double(mrpb_ref5norm[,1])[oT_5norm],MAPD_ref5norm[,1][oT_5norm],f=1/4),col=cols[1],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,1])[oT_327norm],MAPD_ref327norm[,1][oT_327norm],f=1/4),col=cols[2],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,1])[oT_10tum],MAPD_ref10tum[,1][oT_10tum],f=1/4),col=cols[3],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,1])[oT_flat],MAPD_refFlat_nonadj[,1][oT_flat],f=1/4),col=cols[4],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,1])[oT_flat],MAPD_refFlat_adj[,1][oT_flat],f=1/4),col=cols[5],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,1])[oT_flat],MAPD_refFlat_func_adj[,1][oT_flat],f=1/4),col=cols[6],lty=1,type="l",lwd=2)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "PCA cluster cor","PCA function cor", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),lty=c(NA,rep(1,6),NA,1,2),lwd=c(NA,rep(2,6),NA,1,1))
dev.off()

#Two plots in the same, targets only and antitargets only
filename_MAPD <- "MAPD_comp_refs_with_wgs_smooth_lines_2plotTargAtarg.jpeg"
jpeg(filename_MAPD,width=9,height=7.5,quality=90,units="in",res=600)
layout(matrix(1:2,1,2))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on antitargets',log="x",ylim=c(0,0.5),xlim=c(20,650),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(lowess(as.double(mrpb_ref5norm[,2])[oAT_5norm],MAPD_ref5norm[,2][oAT_5norm],f=1/4),col=cols[1],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,2])[oAT_327norm],MAPD_ref327norm[,2][oAT_327norm],f=1/4),col=cols[2],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,2])[oAT_10tum],MAPD_ref10tum[,2][oAT_10tum],f=1/4),col=cols[3],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,2])[oAT_flat],MAPD_refFlat_nonadj[,2][oAT_flat],f=1/4),col=cols[4],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,2])[oAT_flat],MAPD_refFlat_adj[,2][oAT_flat],f=1/4),col=cols[5],lty=3,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,2])[oAT_flat],MAPD_refFlat_func_adj[,2][oAT_flat],f=1/4),col=cols[6],lty=3,type="l",lwd=2)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor + pca clust adj","GC cor + pca funct adj", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),lty=c(NA,rep(3,6),NA,1,2),lwd=c(NA,rep(2,6),NA,1,1))

plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2 CN ratio)',type='l',main='zoom in on targets',log="x",ylim=c(0,0.25),xlim=c(650,3000),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(lowess(as.double(mrpb_ref5norm[,1])[oT_5norm],MAPD_ref5norm[,1][oT_5norm],f=1/4),col=cols[1],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref327norm[,1])[oT_327norm],MAPD_ref327norm[,1][oT_327norm],f=1/4),col=cols[2],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_ref10tum[,1])[oT_10tum],MAPD_ref10tum[,1][oT_10tum],f=1/4),col=cols[3],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_nonadj[,1])[oT_flat],MAPD_refFlat_nonadj[,1][oT_flat],f=1/4),col=cols[4],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_adj[,1])[oT_flat],MAPD_refFlat_adj[,1][oT_flat],f=1/4),col=cols[5],lty=1,type="l",lwd=2)
lines(lowess(as.double(mrpb_refFlat_func_adj[,1])[oT_flat],MAPD_refFlat_func_adj[,1][oT_flat],f=1/4),col=cols[6],lty=1,type="l",lwd=2)
legend_text <- c("reference type:","5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor + pca clust adj","GC cor + pca funct adj", " ", "1 x stochastic process", "2 x stochastic process")
legend("topright",legend_text, col=c(NA,cols[1:6],NA,1,1),lty=c(NA,rep(1,6),NA,1,2),lwd=c(NA,rep(2,6),NA,1,1))
dev.off()

##########

assigned_clust <- as.vector(as.matrix(read.table("/home/rebecka.bergstrom/cnvkit/BREASTv6_all/Rplots/smooth/randTestSet/pca/withoutY/assigend_clust_testset.txt",as.is=TRUE)))
assigned_clust[which(MAPD_refFlat_adj[,1] > MAPD_ref327norm[,1])]

#plot for each cluster
#NOTE, not cpmplete, have to make ordering vectors for each cluster since the indexing changes when I subset into clusters
setwd(path_CNVkit)
filename_MAPD_clust <- "MAPD_comp_refs_clusters.pdf"
pdf(filename_MAPD_clust,width=20,height=9.8)
layout(matrix(1:8,2,4,byrow = TRUE))
par(mar=c(5,4,4,2)+0.1)
#targets
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, targets, cluster 1',log="x",ylim=c(0,0.25),xlim=c(650,3000))
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(as.double(mrpb_ref5norm[which(assigned_clust==1),1])[oT_5norm],MAPD_ref5norm[which(assigned_clust==1),1][oT_5norm],col=cols[1],lty=1)
lines(as.double(mrpb_ref327norm[which(assigned_clust==1),1])[oT_327norm],MAPD_ref327norm[which(assigned_clust==1),1][oT_327norm],col=cols[2],lty=1)
lines(as.double(mrpb_ref10tum[which(assigned_clust==1),1])[oT_10tum],MAPD_ref10tum[which(assigned_clust==1),1][oT_10tum],col=cols[3],lty=1)
lines(as.double(mrpb_refFlat_nonadj[which(assigned_clust==1),1])[oT_flat],MAPD_refFlat_nonadj[which(assigned_clust==1),1][oT_flat],col=cols[4],lty=1)
lines(as.double(mrpb_refFlat_adj[which(assigned_clust==1),1])[oT_flat],MAPD_refFlat_adj[which(assigned_clust==1),1][oT_flat],col=cols[5],lty=1)
lines(as.double(mrpb_refFlat_func_adj[which(assigned_clust==1),1])[oT_flat],MAPD_refFlat_func_adj[which(assigned_clust==1),1][oT_flat],col=cols[6],lty=1)
legend_text <- c("5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor + pca clust adj", "GC cor only + pca funct adj")
legend("topleft",legend_text, col=cols,lty=rep(3,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, targets, cluster 2',log="x",ylim=c(0,0.25),xlim=c(650,3000))
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(as.double(mrpb_ref5norm[which(assigned_clust==2),1])[oT_5norm],MAPD_ref5norm[which(assigned_clust==2),1][oT_5norm],col=cols[1],lty=1)
lines(as.double(mrpb_ref327norm[which(assigned_clust==2),1])[oT_327norm],MAPD_ref327norm[which(assigned_clust==2),1][oT_327norm],col=cols[2],lty=1)
lines(as.double(mrpb_ref10tum[which(assigned_clust==2),1])[oT_10tum],MAPD_ref10tum[which(assigned_clust==2),1][oT_10tum],col=cols[3],lty=1)
lines(as.double(mrpb_refFlat_nonadj[which(assigned_clust==2),1])[oT_flat],MAPD_refFlat_nonadj[which(assigned_clust==2),1][oT_flat],col=cols[4],lty=1)
lines(as.double(mrpb_refFlat_adj[which(assigned_clust==2),1])[oT_flat],MAPD_refFlat_adj[which(assigned_clust==2),1][oT_flat],col=cols[5],lty=1)
lines(as.double(mrpb_refFlat_func_adj[which(assigned_clust==2),1])[oT_flat],MAPD_refFlat_func_adj[which(assigned_clust==2),1][oT_flat],col=cols[6],lty=1)
legend_text <- c("5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor only + pca clust adj", "GC cor only + pca funct adj")
legend("topleft",legend_text, col=cols,lty=rep(3,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, targets, cluster 3',log="x",ylim=c(0,0.25),xlim=c(650,3000))
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(as.double(mrpb_ref5norm[which(assigned_clust==3),1])[oT_5norm],MAPD_ref5norm[which(assigned_clust==3),1][oT_5norm],col=cols[1],lty=1)
lines(as.double(mrpb_ref327norm[which(assigned_clust==3),1])[oT_327norm],MAPD_ref327norm[which(assigned_clust==3),1][oT_327norm],col=cols[2],lty=1)
lines(as.double(mrpb_ref10tum[which(assigned_clust==3),1])[oT_10tum],MAPD_ref10tum[which(assigned_clust==3),1][oT_10tum],col=cols[3],lty=1)
lines(as.double(mrpb_refFlat_nonadj[which(assigned_clust==3),1])[oT_flat],MAPD_refFlat_nonadj[which(assigned_clust==3),1][oT_flat],col=cols[4],lty=1)
lines(as.double(mrpb_refFlat_adj[which(assigned_clust==3),1])[oT_flat],MAPD_refFlat_adj[which(assigned_clust==3),1][oT_flat],col=cols[5],lty=1)
lines(as.double(mrpb_refFlat_func_adj[which(assigned_clust==3),1])[oT_flat],MAPD_refFlat_func_adj[which(assigned_clust==3),1][oT_flat],col=cols[6],lty=1)
legend_text <- c("5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor only + pca clust adj", "GC cor only + pca funct adj")
legend("topright",legend_text, col=cols,lty=rep(3,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, targets, cluster 0',log="x",ylim=c(0,0.25),xlim=c(650,3000))
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(as.double(mrpb_ref5norm[which(assigned_clust==0),1])[oT_5norm],MAPD_ref5norm[which(assigned_clust==0),1][oT_5norm],col=cols[1],lty=1)
lines(as.double(mrpb_ref327norm[which(assigned_clust==0),1])[oT_327norm],MAPD_ref327norm[which(assigned_clust==0),1][oT_327norm],col=cols[2],lty=1)
lines(as.double(mrpb_ref10tum[which(assigned_clust==0),1])[oT_10tum],MAPD_ref10tum[which(assigned_clust==0),1][oT_10tum],col=cols[3],lty=1)
lines(as.double(mrpb_refFlat_nonadj[which(assigned_clust==0),1])[oT_flat],MAPD_refFlat_nonadj[which(assigned_clust==0),1][oT_flat],col=cols[4],lty=1)
lines(as.double(mrpb_refFlat_adj[which(assigned_clust==0),1])[oT_flat],MAPD_refFlat_adj[which(assigned_clust==0),1][oT_flat],col=cols[5],lty=1)
lines(as.double(mrpb_refFlat_func_adj[which(assigned_clust==0),1])[oT_flat],MAPD_refFlat_func_adj[which(assigned_clust==0),1][oT_flat],col=cols[6],lty=1)
legend_text <- c("5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor only + pca clust adj", "GC cor only + pca funct adj")
legend("topright",legend_text, col=cols,lty=rep(3,6))
#antitargets
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, antitargets, cluster 1',log="x",ylim=c(0.1,0.5),xlim=c(20,650))
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(as.double(mrpb_ref5norm[which(assigned_clust==1),2])[oAT_5norm],MAPD_ref5norm[which(assigned_clust==1),2][oAT_5norm],col=cols[1],lty=3)
lines(as.double(mrpb_ref327norm[which(assigned_clust==1),2])[oAT_327norm],MAPD_ref327norm[which(assigned_clust==1),2][oAT_327norm],col=cols[2],lty=3)
lines(as.double(mrpb_ref10tum[which(assigned_clust==1),2])[oAT_10tum],MAPD_ref10tum[which(assigned_clust==1),2][oAT_10tum],col=cols[3],lty=3)
lines(as.double(mrpb_refFlat_nonadj[which(assigned_clust==1),2])[oAT_flat],MAPD_refFlat_nonadj[which(assigned_clust==1),2][oAT_flat],col=cols[4],lty=3)
lines(as.double(mrpb_refFlat_adj[which(assigned_clust==1),2])[oAT_flat],MAPD_refFlat_adj[which(assigned_clust==1),2][oAT_flat],col=cols[5],lty=3)
lines(as.double(mrpb_refFlat_func_adj[which(assigned_clust==1),2])[oAT_flat],MAPD_refFlat_func_adj[which(assigned_clust==1),2][oAT_flat],col=cols[6],lty=3)
legend_text <- c("5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor only + pca clust adj", "GC cor only + pca funct adj")
legend("topright",legend_text, col=cols,lty=rep(4,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, antitargets, cluster 2',log="x",ylim=c(0.1,0.5),xlim=c(20,650))
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(as.double(mrpb_ref5norm[which(assigned_clust==2),2])[oAT_5norm],MAPD_ref5norm[which(assigned_clust==2),2][oAT_5norm],col=cols[1],lty=3)
lines(as.double(mrpb_ref327norm[which(assigned_clust==2),2])[oAT_327norm],MAPD_ref327norm[which(assigned_clust==2),2][oAT_327norm],col=cols[2],lty=3)
lines(as.double(mrpb_ref10tum[which(assigned_clust==2),2])[oAT_10tum],MAPD_ref10tum[which(assigned_clust==2),2][oAT_10tum],col=cols[3],lty=3)
lines(as.double(mrpb_refFlat_nonadj[which(assigned_clust==2),2])[oAT_flat],MAPD_refFlat_nonadj[which(assigned_clust==2),2][oAT_flat],col=cols[4],lty=3)
lines(as.double(mrpb_refFlat_adj[which(assigned_clust==2),2])[oAT_flat],MAPD_refFlat_adj[which(assigned_clust==2),2][oAT_flat],col=cols[5],lty=3)
lines(as.double(mrpb_refFlat_func_adj[which(assigned_clust==2),2])[oAT_flat],MAPD_refFlat_func_adj[which(assigned_clust==2),2][oAT_flat],col=cols[6],lty=3)
legend_text <- c("5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor only + pca clust adj", "GC cor only + pca funct adj")
legend("topright",legend_text, col=cols,lty=rep(4,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, antitargets, cluster 3',log="x",ylim=c(0.1,0.5),xlim=c(20,650))
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(as.double(mrpb_ref5norm[which(assigned_clust==3),2])[oAT_5norm],MAPD_ref5norm[which(assigned_clust==3),2][oAT_5norm],col=cols[1],lty=3)
lines(as.double(mrpb_ref327norm[which(assigned_clust==3),2])[oAT_327norm],MAPD_ref327norm[which(assigned_clust==3),2][oAT_327norm],col=cols[2],lty=3)
lines(as.double(mrpb_ref10tum[which(assigned_clust==3),2])[oAT_10tum],MAPD_ref10tum[which(assigned_clust==3),2][oAT_10tum],col=cols[3],lty=3)
lines(as.double(mrpb_refFlat_nonadj[which(assigned_clust==3),2])[oAT_flat],MAPD_refFlat_nonadj[which(assigned_clust==3),2][oAT_flat],col=cols[4],lty=3)
lines(as.double(mrpb_refFlat_adj[which(assigned_clust==3),2])[oAT_flat],MAPD_refFlat_adj[which(assigned_clust==3),2][oAT_flat],col=cols[5],lty=3)
lines(as.double(mrpb_refFlat_func_adj[which(assigned_clust==3),2])[oAT_flat],MAPD_refFlat_func_adj[which(assigned_clust==3),2][oAT_flat],col=cols[6],lty=3)
legend_text <- c("5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor only + pca clust adj", "GC cor only + pca funct adj")
legend("topright",legend_text, col=cols,lty=rep(4,6))
plot(reads,mapd,xlab='median #reads per bin',ylab='median absolute pairwise difference (log2CNratio)',type='l',main='MAPD, Bv6 50 samples, antitargets, cluster 0',log="x",ylim=c(0.1,0.5),xlim=c(20,650))
points(reads, mapd*sqrt(2),type="l",lty=2)
lines(as.double(mrpb_ref5norm[which(assigned_clust==0),2])[oAT_5norm],MAPD_ref5norm[which(assigned_clust==0),2][oAT_5norm],col=cols[1],lty=3)
lines(as.double(mrpb_ref327norm[which(assigned_clust==0),2])[oAT_327norm],MAPD_ref327norm[which(assigned_clust==0),2][oAT_327norm],col=cols[2],lty=3)
lines(as.double(mrpb_ref10tum[which(assigned_clust==0),2])[oAT_10tum],MAPD_ref10tum[which(assigned_clust==0),2][oAT_10tum],col=cols[3],lty=3)
lines(as.double(mrpb_refFlat_nonadj[which(assigned_clust==0),2])[oAT_flat],MAPD_refFlat_nonadj[which(assigned_clust==0),2][oAT_flat],col=cols[4],lty=3)
lines(as.double(mrpb_refFlat_adj[which(assigned_clust==0),2])[oAT_flat],MAPD_refFlat_adj[which(assigned_clust==0),2][oAT_flat],col=cols[5],lty=3)
lines(as.double(mrpb_refFlat_func_adj[which(assigned_clust==0),2])[oAT_flat],MAPD_refFlat_func_adj[which(assigned_clust==0),2][oAT_flat],col=cols[6],lty=3)
legend_text <- c("5 normals", "327 normals", "10 tumors", "GC cor only", "GC cor only + pca clust adj", "GC cor only + pca funct adj")
legend("topright",legend_text, col=cols,lty=rep(4,6))
dev.off()