#Save plots from pca analysis for inclusion in report
#Created by Rebecka Bergström on 2016-04-21

library(MASS)

load("/home/rebecka.bergstrom/cnvkit/BREASTv6_all/Rplots/smooth/randTestSet/pca/withoutY/.RData")
setwd("/home/rebecka.bergstrom/cnvkit/BREASTv6_all/Rplots/smooth/randTestSet/pca/withoutY/forReport/")

##################

#Show which PCs are relevant to use for basing bin value adjustments on

#PC1 vs PC2 etc to PC8 vs PC9
filename_pca <- "pca_Bv6_allTumors_woY.jpeg"
jpeg(filename_pca,width=9,height=5,quality=90,units="in",res=600)
layout(matrix(c(1:8),2,4, byrow = TRUE))
par(mar=c(5, 4.3, 2, 2) + 0.1)
plot(pca_refFlat$x[,2],pca_refFlat$x[,1],xlab="PC2",ylab="PC1",xlim=c(-130,130),ylim=c(-130,130),cex.axis=1.5,cex.lab=1.5,pch=16,col="#00000050")
plot(pca_refFlat$x[,3],pca_refFlat$x[,2],xlab="PC3",ylab="PC2",xlim=c(-130,130),ylim=c(-130,130),cex.axis=1.5,cex.lab=1.5,pch=16,col="#00000050")
plot(pca_refFlat$x[,4],pca_refFlat$x[,3],xlab="PC4",ylab="PC3",xlim=c(-130,130),ylim=c(-130,130),cex.axis=1.5,cex.lab=1.5,pch=16,col="#00000050")
plot(pca_refFlat$x[,5],pca_refFlat$x[,4],xlab="PC5",ylab="PC4",xlim=c(-130,130),ylim=c(-130,130),cex.axis=1.5,cex.lab=1.5,pch=16,col="#00000050")
plot(pca_refFlat$x[,6],pca_refFlat$x[,5],xlab="PC6",ylab="PC5",xlim=c(-130,130),ylim=c(-130,130),cex.axis=1.5,cex.lab=1.5,pch=16,col="#00000050")
plot(pca_refFlat$x[,7],pca_refFlat$x[,6],xlab="PC7",ylab="PC6",xlim=c(-130,130),ylim=c(-130,130),cex.axis=1.5,cex.lab=1.5,pch=16,col="#00000050")
plot(pca_refFlat$x[,8],pca_refFlat$x[,7],xlab="PC8",ylab="PC7",xlim=c(-130,130),ylim=c(-130,130),cex.axis=1.5,cex.lab=1.5,pch=16,col="#00000050")
plot(pca_refFlat$x[,9],pca_refFlat$x[,8],xlab="PC9",ylab="PC8",xlim=c(-130,130),ylim=c(-130,130),cex.axis=1.5,cex.lab=1.5,pch=16,col="#00000050")
dev.off()

#compare standard deviations in each PC with negative ctrl (shuffled)
filename_negctrl <- "pca_compNegCtrl_Bv6_woY_barSD.jpeg"
jpeg(filename_negctrl,width=9,height=9,quality=90,units="in",res=600)
layout(matrix(c(1,2),2,1,byrow=TRUE))
par(mar=c(5,4.3,4,1.7)+0.1)
barplot(pca_refFlat$sdev,ylim=c(0,30),xlab="PC",ylab="Standard deviation",main="SD per PC, pca on tumor samples",names.arg=1:284,col=gray.colors(284,start=0.99,end=0.2),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
barplot(pca_shuff$sdev,ylim=c(0,30),xlab="PC",ylab="Standard deviation",main="SD per PC, pca on neg ctrl",names.arg=1:284,col=gray.colors(284,start=0.99,end=0.2),cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
dev.off()
filename_negctrl <- "pca_compNegCtrl_Bv6_woY_SDvsSD.jpeg"
jpeg(filename_negctrl,width=9,height=9,quality=90,units="in",res=600)
layout(1,1,1)
par(mar=c(4.5,4.3,2.8,1.7)+0.1)
plot(pca_shuff$sdev,pca_refFlat$sdev,xlim=c(0,27),ylim=c(0,27),xlab="SD per PC, neg ctrl",ylab="SD per PC, tumor samples",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
fit<-rlm(pca_refFlat$sdev ~ pca_shuff$sdev)
points(pca_shuff$sdev,fit$fitted.values,type="l")
legend("topleft",c("PCs",paste("Fitted line, slope = ",signif(fit$coefficients[[2]],digits=3),", interc = ",signif(fit$coefficients[[1]],digits=3),sep="")),lty=c(NA,1),pch=c(1,NA),col=1,cex=1.2)
dev.off()

#############

#Show correlations to pca on smoothed values, not very important
layout(matrix(1,1,1))
barplot(cor_err_smooth[1:6,1:6], las=2, beside=TRUE,xlab="PCs from pca on smoothed values")
legend(y=-0.15,x=12,paste("PC",1:6," from pca on error",sep=""),fill=grey.colors(6))
#error-PC1 & PC2 vs smooth-PC6
layout(matrix(1:2,1,2,byrow=TRUE))
plot(pca_smooth$x[,6],pca_refFlat$x[,1],type="n",main=paste("cor =",signif(cor_err_smooth[1,6],2)))
points(pca_smooth$x[clInd1,6],pca_refFlat$x[clInd1,1],col="red")
points(pca_smooth$x[clInd2,6],pca_refFlat$x[clInd2,1],col="green")
points(pca_smooth$x[clInd3,6],pca_refFlat$x[clInd3,1],col="blue")
points(pca_smooth$x[clInd0,6],pca_refFlat$x[clInd0,1],col="black")
plot(pca_smooth$x[,6],pca_refFlat$x[,2],type="n",main=paste("cor =",signif(cor_err_smooth[2,6],2)))
points(pca_smooth$x[clInd1,6],pca_refFlat$x[clInd1,2],col="red")
points(pca_smooth$x[clInd2,6],pca_refFlat$x[clInd2,2],col="green")
points(pca_smooth$x[clInd3,6],pca_refFlat$x[clInd3,2],col="blue")
points(pca_smooth$x[clInd0,6],pca_refFlat$x[clInd0,2],col="black")

layout(matrix(1,1,1))
plot(pca_refFlat$rotation[,1])
plot(pca_refFlat$rotation[,2])
plot(pca_refFlat$rotation[,3])
plot(pca_refFlat$rotation[,6])
plot(pca_smooth$rotation[,1])
plot(pca_smooth$rotation[,6])

barplot(cor_err_smooth_total[1:7,1:7], las=2, beside=TRUE,xlab="PCs from pca on smoothed values")


############

#Show that we have no correlation to CNVs by plotting of loadings
filename_loadings <- "pca_loadings_PC1-4.jpeg"
jpeg(filename_loadings,width=9,height=3,quality=90,units="in",res=600)
layout(matrix(1:4,1,4,byrow=TRUE))
par(mar=c(4.2,4.3,2.8,1.7)+0.1)
plot(dat_cnr_tumors_refFlat$startcoord[-Ybins],pca_refFlat$rotation[,1],ylim=c(-0.07,0.07),cex=0.5,pch=16,col="#00000060",xlab="Chromosome #",ylab="loadings PC1",cex.axis=1.5,cex.lab=1.5,xaxt="n")
abline(v=c(chr_coord$start,chr_coord$end[24]), lty=3, lwd=0.5) #vertical lines for the chromosomes and horizontal for neutral log2CN
axis(1, at=xticks, label=c(1:22,"X","Y"),cex.axis=1.5)
plot(dat_cnr_tumors_refFlat$startcoord[-Ybins],pca_refFlat$rotation[,2],ylim=c(-0.07,0.07),cex=0.5,pch=16,col="#00000060",xlab="Chromosome #",ylab="loadings PC2",cex.axis=1.5,cex.lab=1.5,xaxt="n")
abline(v=c(chr_coord$start,chr_coord$end[24]), lty=3, lwd=0.5) #vertical lines for the chromosomes and horizontal for neutral log2CN
axis(1, at=xticks, label=c(1:22,"X","Y"),cex.axis=1.5)
plot(dat_cnr_tumors_refFlat$startcoord[-Ybins],pca_refFlat$rotation[,3],ylim=c(-0.07,0.07),cex=0.5,pch=16,col="#00000060",xlab="Chromosome #",ylab="loadings PC3",cex.axis=1.5,cex.lab=1.5,xaxt="n")
abline(v=c(chr_coord$start,chr_coord$end[24]), lty=3, lwd=0.5) #vertical lines for the chromosomes and horizontal for neutral log2CN
axis(1, at=xticks, label=c(1:22,"X","Y"),cex.axis=1.5)
plot(dat_cnr_tumors_refFlat$startcoord[-Ybins],pca_refFlat$rotation[,4],ylim=c(-0.07,0.07),cex=0.5,pch=16,col="#00000060",xlab="Chromosome #",ylab="loadings PC4",cex.axis=1.5,cex.lab=1.5,xaxt="n")
abline(v=c(chr_coord$start,chr_coord$end[24]), lty=3, lwd=0.5) #vertical lines for the chromosomes and horizontal for neutral log2CN
axis(1, at=xticks, label=c(1:22,"X","Y"),cex.axis=1.5)
dev.off()

############

#Show how clusters separate on PC1-4
filename_clustSep <- "pca_clustSep_PC1-4.jpeg"
jpeg(filename_clustSep,width=9,height=7,quality=90,units="in",res=600)
layout(matrix(1:6,2,3,byrow=TRUE))
par(mar=c(4.5,4.4,3.7,1.8)+0.1)
plot(x_inter[,1],x_inter[,2],type="n",xlab="PC1",ylab="PC2",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,1],x_inter[clInd1,2],col="red")
points(x_inter[clInd2,1],x_inter[clInd2,2],col="green")
points(x_inter[clInd3,1],x_inter[clInd3,2],col="blue")
points(x_inter[clInd0,1],x_inter[clInd0,2],col="black")
legend("topright",c("cluster 1","cluster 2","cluster 3","outliers"),col=c("red","green","blue","black"),pch=1)
plot(x_inter[,1],x_inter[,3],type="n",xlab="PC1",ylab="PC3",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,1],x_inter[clInd1,3],col="red")
points(x_inter[clInd2,1],x_inter[clInd2,3],col="green")
points(x_inter[clInd3,1],x_inter[clInd3,3],col="blue")
points(x_inter[clInd0,1],x_inter[clInd0,3],col="black")
plot(x_inter[,1],x_inter[,4],type="n",xlab="PC1",ylab="PC4",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,1],x_inter[clInd1,4],col="red")
points(x_inter[clInd2,1],x_inter[clInd2,4],col="green")
points(x_inter[clInd3,1],x_inter[clInd3,4],col="blue")
points(x_inter[clInd0,1],x_inter[clInd0,4],col="black")
plot(x_inter[,2],x_inter[,3],type="n",xlab="PC2",ylab="PC3",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,2],x_inter[clInd1,3],col="red")
points(x_inter[clInd2,2],x_inter[clInd2,3],col="green")
points(x_inter[clInd3,2],x_inter[clInd3,3],col="blue")
points(x_inter[clInd0,2],x_inter[clInd0,3],col="black")
plot(x_inter[,2],x_inter[,4],type="n",xlab="PC2",ylab="PC4",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,2],x_inter[clInd1,4],col="red")
points(x_inter[clInd2,2],x_inter[clInd2,4],col="green")
points(x_inter[clInd3,2],x_inter[clInd3,4],col="blue")
points(x_inter[clInd0,2],x_inter[clInd0,4],col="black")
plot(x_inter[,3],x_inter[,4],type="n",xlab="PC3",ylab="PC4",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,3],x_inter[clInd1,4],col="red")
points(x_inter[clInd2,3],x_inter[clInd2,4],col="green")
points(x_inter[clInd3,3],x_inter[clInd3,4],col="blue")
points(x_inter[clInd0,3],x_inter[clInd0,4],col="black")
dev.off()

plot3d(x_inter[,1],x_inter[,2],x_inter[,3],type="n", main=paste("eps =",Eps," eps_cl =",Eps_cl))
points3d(x_inter[clInd1,1],x_inter[clInd1,2],x_inter[clInd1,3],col="red")
points3d(x_inter[clInd2,1],x_inter[clInd2,2],x_inter[clInd2,3],col="green")
points3d(x_inter[clInd3,1],x_inter[clInd3,2],x_inter[clInd3,3],col="blue")
points3d(x_inter[clInd0,1],x_inter[clInd0,2],x_inter[clInd0,3],col="black")
points3d(x_inter[,1],x_inter[,2],rep(-60,length(x_inter[,1])),col="grey")
points3d(x_inter[,1],rep(-60,length(x_inter[,1])),x_inter[,3],col="grey")
points3d(rep(-60,length(x_inter[,1])),x_inter[,2],x_inter[,3],col="grey")

layout(matrix(1,1,1))
scatterplot3d(x_inter[,1],x_inter[,2],x_inter[,3],highlight.3d = TRUE,pch=" ",type="h")

############

#Show that the assigned clusters of the test samples are correctly assigned
filename_clustSep_assigned <- "pca_clustSep_assigned_PC1-4.jpeg"
jpeg(filename_clustSep_assigned,width=9,height=7,quality=90,units="in",res=600)
layout(matrix(1:6,2,3,byrow=TRUE))
par(mar=c(4.5,4.4,3.7,1.8)+0.1)
plot(x_inter[,1],x_inter[,2],type="n",xlab="PC1",ylab="PC2",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,1],x_inter[clInd1,2],col="red")
points(x_inter[clInd2,1],x_inter[clInd2,2],col="green")
points(x_inter[clInd3,1],x_inter[clInd3,2],col="blue")
points(x_inter[clInd0,1],x_inter[clInd0,2],col="black")
points(pc_test_all[which(assign_clust_all==1),1],pc_test_all[which(assign_clust_all==1),2],col="red",pch=8)
points(pc_test_all[which(assign_clust_all==2),1],pc_test_all[which(assign_clust_all==2),2],col="green",pch=8)
points(pc_test_all[which(assign_clust_all==3),1],pc_test_all[which(assign_clust_all==3),2],col="blue",pch=8)
points(pc_test_all[which(assign_clust_all==0),1],pc_test_all[which(assign_clust_all==0),2],col="black",pch=8)
legend("topleft",c(paste("ref, cluster",1:3),"ref, outliers"),col=c("red","green","blue","black"),pch=rep(1,4))
legend("topright",c(paste("test, cluster",1:3),"test, outliers"),col=c("red","green","blue","black"),pch=rep(8,4))
plot(x_inter[,1],x_inter[,3],type="n",xlab="PC1",ylab="PC3",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,1],x_inter[clInd1,3],col="red")
points(x_inter[clInd2,1],x_inter[clInd2,3],col="green")
points(x_inter[clInd3,1],x_inter[clInd3,3],col="blue")
points(x_inter[clInd0,1],x_inter[clInd0,3],col="black")
points(pc_test_all[which(assign_clust_all==1),1],pc_test_all[which(assign_clust_all==1),3],col="red",pch=8)
points(pc_test_all[which(assign_clust_all==2),1],pc_test_all[which(assign_clust_all==2),3],col="green",pch=8)
points(pc_test_all[which(assign_clust_all==3),1],pc_test_all[which(assign_clust_all==3),3],col="blue",pch=8)
points(pc_test_all[which(assign_clust_all==0),1],pc_test_all[which(assign_clust_all==0),3],col="black",pch=8)
plot(x_inter[,1],x_inter[,4],type="n",xlab="PC1",ylab="PC4",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,1],x_inter[clInd1,4],col="red")
points(x_inter[clInd2,1],x_inter[clInd2,4],col="green")
points(x_inter[clInd3,1],x_inter[clInd3,4],col="blue")
points(x_inter[clInd0,1],x_inter[clInd0,4],col="black")
points(pc_test_all[which(assign_clust_all==1),1],pc_test_all[which(assign_clust_all==1),4],col="red",pch=8)
points(pc_test_all[which(assign_clust_all==2),1],pc_test_all[which(assign_clust_all==2),4],col="green",pch=8)
points(pc_test_all[which(assign_clust_all==3),1],pc_test_all[which(assign_clust_all==3),4],col="blue",pch=8)
points(pc_test_all[which(assign_clust_all==0),1],pc_test_all[which(assign_clust_all==0),4],col="black",pch=8)
plot(x_inter[,2],x_inter[,3],type="n",xlab="PC2",ylab="PC3",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,2],x_inter[clInd1,3],col="red")
points(x_inter[clInd2,2],x_inter[clInd2,3],col="green")
points(x_inter[clInd3,2],x_inter[clInd3,3],col="blue")
points(x_inter[clInd0,2],x_inter[clInd0,3],col="black")
points(pc_test_all[which(assign_clust_all==1),2],pc_test_all[which(assign_clust_all==1),3],col="red",pch=8)
points(pc_test_all[which(assign_clust_all==2),2],pc_test_all[which(assign_clust_all==2),3],col="green",pch=8)
points(pc_test_all[which(assign_clust_all==3),2],pc_test_all[which(assign_clust_all==3),3],col="blue",pch=8)
points(pc_test_all[which(assign_clust_all==0),2],pc_test_all[which(assign_clust_all==0),3],col="black",pch=8)
plot(x_inter[,2],x_inter[,4],type="n",xlab="PC2",ylab="PC4",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,2],x_inter[clInd1,4],col="red")
points(x_inter[clInd2,2],x_inter[clInd2,4],col="green")
points(x_inter[clInd3,2],x_inter[clInd3,4],col="blue")
points(pc_test_all[which(assign_clust_all==1),2],pc_test_all[which(assign_clust_all==1),4],col="red",pch=8)
points(pc_test_all[which(assign_clust_all==2),2],pc_test_all[which(assign_clust_all==2),4],col="green",pch=8)
points(pc_test_all[which(assign_clust_all==3),2],pc_test_all[which(assign_clust_all==3),4],col="blue",pch=8)
points(pc_test_all[which(assign_clust_all==0),2],pc_test_all[which(assign_clust_all==0),4],col="black",pch=8)
points(x_inter[clInd0,2],x_inter[clInd0,4],col="black")
plot(x_inter[,3],x_inter[,4],type="n",xlab="PC3",ylab="PC4",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,3],x_inter[clInd1,4],col="red")
points(x_inter[clInd2,3],x_inter[clInd2,4],col="green")
points(x_inter[clInd3,3],x_inter[clInd3,4],col="blue")
points(x_inter[clInd0,3],x_inter[clInd0,4],col="black")
points(pc_test_all[which(assign_clust_all==1),3],pc_test_all[which(assign_clust_all==1),4],col="red",pch=8)
points(pc_test_all[which(assign_clust_all==2),3],pc_test_all[which(assign_clust_all==2),4],col="green",pch=8)
points(pc_test_all[which(assign_clust_all==3),3],pc_test_all[which(assign_clust_all==3),4],col="blue",pch=8)
points(pc_test_all[which(assign_clust_all==0),3],pc_test_all[which(assign_clust_all==0),4],col="black",pch=8)
dev.off()

#Show that the assigned clusters of the test samples are correctly assigned, PC1-2 only
filename_clustSep_assigned <- "pca_clustSep_assigned_PC1-2.jpeg"
jpeg(filename_clustSep_assigned,width=9,height=7,quality=90,units="in",res=600)
layout(matrix(1,1,1,byrow=TRUE))
par(mar=c(4.5,4.4,2.0,1.8)+0.1)
plot(x_inter[,1],x_inter[,2],type="n",xlab="PC1",ylab="PC2",xlim=c(-85,85),ylim=c(-85,85),cex.lab=1.5,cex.axis=1.5)
points(x_inter[clInd1,1],x_inter[clInd1,2],col="red")
points(x_inter[clInd2,1],x_inter[clInd2,2],col="green")
points(x_inter[clInd3,1],x_inter[clInd3,2],col="blue")
points(x_inter[clInd0,1],x_inter[clInd0,2],col="black")
points(pc_test_all[which(assign_clust_all==1),1],pc_test_all[which(assign_clust_all==1),2],col="red",pch=8)
points(pc_test_all[which(assign_clust_all==2),1],pc_test_all[which(assign_clust_all==2),2],col="green",pch=8)
points(pc_test_all[which(assign_clust_all==3),1],pc_test_all[which(assign_clust_all==3),2],col="blue",pch=8)
points(pc_test_all[which(assign_clust_all==0),1],pc_test_all[which(assign_clust_all==0),2],col="black",pch=8)
legend("topleft",c(paste("ref, cluster",1:3),"ref, outliers"),col=c("red","green","blue","black"),pch=rep(1,4),cex=1.5)
legend("topright",c(paste("test, cluster",1:3),"test, outliers"),col=c("red","green","blue","black"),pch=rep(8,4),cex=1.5)
dev.off()

##########

#Show that the distribution of clusters are the same in original and assigned clusters
filename_clust_distr <- "pca_clust_distr.jpeg"
jpeg(filename_clust_distr,width=9,height=4.5,quality=90,units="in",res=600)
layout(matrix(c(1,2),1,2))
par(mar=c(4.5,4.5,3.7,1.8)+0.1)
hist(opt$cluster,freq=FALSE,main="Samples spanning the pca space",xlab="cluster",ylab="% of samples",cex.main=1,breaks=c(-0.5,0.5,1.5,2.5,3.5),xaxt="n",yaxt="n",col=c("black","red","green","blue"),ylim=c(0,0.65))
axis(1,at=0:3,labels=c("outliers",1:3))
axis(2,at=seq(0,0.6,0.1),labels=seq(0,0.6,0.1)*100)
hist(assign_clust_all,freq=FALSE,main="Samples rotated into the pca space",xlab="assigned cluster",ylab="% of samples",cex.main=1,breaks=c(-0.5,0.5,1.5,2.5,3.5),xaxt="n",yaxt="n",col=c("black","red","green","blue"),ylim=c(0,0.65))
axis(1,at=0:3,labels=c("outliers",1:3))
axis(2,at=seq(0,0.6,0.1),labels=seq(0,0.6,0.1)*100)
dev.off()


########################################

#Show correlations to MAPD and mrpb
cor_MAPD_targ <- cor(pca_refFlat$x[,1:4],as.numeric(MAPD_targets_refFlat[-as.integer(testset[,2]),2]),method="s")
cor_MAPD_antitarg <- cor(pca_refFlat$x[,1:4],as.numeric(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2]),method="s")
filename_corMAPD <- "cor_MAPD_PC1-4.jpeg"
jpeg(filename_corMAPD,width=9,height=6,quality=90,units="in",res=600)
layout(matrix(1:8,nrow=2,ncol=4,byrow=TRUE))
par(mar=c(4.5,4.3,3.8,1.7)+0.1)
plot(MAPD_targets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,1],ylab="PC1",xlab="MAPD targets",main=paste("correlation =",signif(cor_MAPD_targ[1],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,1],col="red")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,1],col="green")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,1],col="blue")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,1],col="black")
legend("topleft",c("cluster 1","cluster 2","cluster 3","outliers"),col=c("red","green","blue","black"),pch=1)
plot(MAPD_targets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,2],ylab="PC2",xlab="MAPD targets",main=paste("correlation =",signif(cor_MAPD_targ[2],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,2],col="red")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,2],col="green")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,2],col="blue")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,2],col="black")
plot(MAPD_targets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,3],ylab="PC3",xlab="MAPD targets",main=paste("correlation =",signif(cor_MAPD_targ[3],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,3],col="red")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,3],col="green")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,3],col="blue")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,3],col="black")
plot(MAPD_targets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,4],ylab="PC4",xlab="MAPD targets",main=paste("correlation =",signif(cor_MAPD_targ[4],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,4],col="red")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,4],col="green")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,4],col="blue")
points(MAPD_targets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,4],col="black")
plot(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,1],ylab="PC1",xlab="MAPD antitargets",main=paste("correlation =",signif(cor_MAPD_antitarg[1],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,1],col="red")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,1],col="green")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,1],col="blue")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,1],col="black")
plot(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,2],ylab="PC2",xlab="MAPD antitargets",main=paste("correlation =",signif(cor_MAPD_antitarg[2],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,2],col="red")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,2],col="green")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,2],col="blue")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,2],col="black")
plot(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,3],ylab="PC3",xlab="MAPD antitargets",main=paste("correlation =",signif(cor_MAPD_antitarg[3],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,3],col="red")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,3],col="green")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,3],col="blue")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,3],col="black")
plot(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,4],ylab="PC4",xlab="MAPD antitargets",main=paste("correlation =",signif(cor_MAPD_antitarg[4],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,4],col="red")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,4],col="green")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,4],col="blue")
points(MAPD_antitargets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,4],col="black")
dev.off()

cor_mrpb_targ <- cor(pca_refFlat$x[,1:4],as.numeric(mrpb_targets_refFlat[-as.integer(testset[,2]),2]),method="s")
cor_mrpb_antitarg <- cor(pca_refFlat$x[,1:4],as.numeric(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2]),method="s")
filename_cormrpb <- "cor_mrpb_PC1-4.jpeg"
jpeg(filename_cormrpb,width=9,height=6,quality=90,units="in",res=600)
layout(matrix(1:8,nrow=2,ncol=4,byrow=TRUE))
par(mar=c(4.5,4.3,3.8,1.7)+0.1)
plot(mrpb_targets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,1],ylab="PC1",xlab="mrpb targets",main=paste("correlation =",signif(cor_mrpb_targ[1],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,1],col="red")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,1],col="green")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,1],col="blue")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,1],col="black")
legend("topright",c("cluster 1","cluster 2","cluster 3","outliers"),col=c("red","green","blue","black"),pch=1)
plot(mrpb_targets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,2],ylab="PC2",xlab="mrpb targets",main=paste("correlation =",signif(cor_mrpb_targ[2],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,2],col="red")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,2],col="green")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,2],col="blue")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,2],col="black")
plot(mrpb_targets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,3],ylab="PC3",xlab="mrpb targets",main=paste("correlation =",signif(cor_mrpb_targ[3],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,3],col="red")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,3],col="green")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,3],col="blue")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,3],col="black")
plot(mrpb_targets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,4],ylab="PC4",xlab="mrpb targets",main=paste("correlation =",signif(cor_mrpb_targ[4],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,4],col="red")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,4],col="green")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,4],col="blue")
points(mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,4],col="black")
plot(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,1],ylab="PC1",xlab="mrpb antitargets",main=paste("correlation =",signif(cor_mrpb_antitarg[1],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,1],col="red")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,1],col="green")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,1],col="blue")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,1],col="black")
plot(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,2],ylab="PC2",xlab="mrpb antitargets",main=paste("correlation =",signif(cor_mrpb_antitarg[2],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,2],col="red")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,2],col="green")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,2],col="blue")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,2],col="black")
plot(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,3],ylab="PC3",xlab="mrpb antitargets",main=paste("correlation =",signif(cor_mrpb_antitarg[3],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,3],col="red")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,3],col="green")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,3],col="blue")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,3],col="black")
plot(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2],pca_refFlat$x[,4],ylab="PC4",xlab="mrpb antitargets",main=paste("correlation =",signif(cor_mrpb_antitarg[4],2)),type="n",cex.main=1.5,cex.axis=1.5,cex.lab=1.5)
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd1],pca_refFlat$x[clInd1,4],col="red")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd2],pca_refFlat$x[clInd2,4],col="green")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd3],pca_refFlat$x[clInd3,4],col="blue")
points(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd0],pca_refFlat$x[clInd0,4],col="black")
dev.off()

###################

#Show correlations with total read counts and on-target rate
cor_tot_reads <- cor(x_inter,tot_reads[-as.integer(testset[,2]),1],method="s")
cor_ontarget_rate <- cor(x_inter,tot_reads[-as.integer(testset[,2]),2],method="s")
filename_cor_totreads <- "cor_totReads_onTargetRate_PC1-4.jpeg"
jpeg(filename_cor_totreads,width=9,height=6,quality=90,units="in",res=600)
layout(matrix(1:8,2,4,byrow=TRUE))
par(mar=c(4.5,4.4,3.7,1.8)+0.1)
plot(tot_reads[-as.integer(testset[,2]),1],x_inter[,1],type="n",xlab="total #reads",ylab="PC1",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_tot_reads[1],2)))
points(tot_reads[-as.integer(testset[,2]),1][clInd1],x_inter[,1][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),1][clInd2],x_inter[,1][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),1][clInd3],x_inter[,1][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),1][clInd0],x_inter[,1][clInd0],col="black")
legend("topright",c("cluster 1","cluster 2","cluster 3","outliers"),col=c("red","green","blue","black"),pch=1)
plot(tot_reads[-as.integer(testset[,2]),1],x_inter[,2],type="n",xlab="total #reads",ylab="PC2",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_tot_reads[2],2)))
points(tot_reads[-as.integer(testset[,2]),1][clInd1],x_inter[,2][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),1][clInd2],x_inter[,2][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),1][clInd3],x_inter[,2][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),1][clInd0],x_inter[,2][clInd0],col="black")
plot(tot_reads[-as.integer(testset[,2]),1],x_inter[,3],type="n",xlab="total #reads",ylab="PC3",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_tot_reads[3],2)))
points(tot_reads[-as.integer(testset[,2]),1][clInd1],x_inter[,3][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),1][clInd2],x_inter[,3][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),1][clInd3],x_inter[,3][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),1][clInd0],x_inter[,3][clInd0],col="black")
plot(tot_reads[-as.integer(testset[,2]),1],x_inter[,4],type="n",xlab="total #reads",ylab="PC4",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_tot_reads[4],2)))
points(tot_reads[-as.integer(testset[,2]),1][clInd1],x_inter[,4][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),1][clInd2],x_inter[,4][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),1][clInd3],x_inter[,4][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),1][clInd0],x_inter[,4][clInd0],col="black")
plot(tot_reads[-as.integer(testset[,2]),2],x_inter[,1],type="n",xlab="on-target rate",ylab="PC1",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_ontarget_rate[1],2)))
points(tot_reads[-as.integer(testset[,2]),2][clInd1],x_inter[,1][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),2][clInd2],x_inter[,1][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),2][clInd3],x_inter[,1][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),2][clInd0],x_inter[,1][clInd0],col="black")
plot(tot_reads[-as.integer(testset[,2]),2],x_inter[,2],type="n",xlab="on-target rate",ylab="PC2",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_ontarget_rate[2],2)))
points(tot_reads[-as.integer(testset[,2]),2][clInd1],x_inter[,2][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),2][clInd2],x_inter[,2][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),2][clInd3],x_inter[,2][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),2][clInd0],x_inter[,2][clInd0],col="black")
plot(tot_reads[-as.integer(testset[,2]),2],x_inter[,3],type="n",xlab="on-target rate",ylab="PC3",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_ontarget_rate[3],2)))
points(tot_reads[-as.integer(testset[,2]),2][clInd1],x_inter[,3][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),2][clInd2],x_inter[,3][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),2][clInd3],x_inter[,3][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),2][clInd0],x_inter[,3][clInd0],col="black")
plot(tot_reads[-as.integer(testset[,2]),2],x_inter[,4],type="n",xlab="on-target rate",ylab="PC4",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_ontarget_rate[4],2)))
points(tot_reads[-as.integer(testset[,2]),2][clInd1],x_inter[,4][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),2][clInd2],x_inter[,4][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),2][clInd3],x_inter[,4][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),2][clInd0],x_inter[,4][clInd0],col="black")
dev.off()

############

#Barplot all previous correlations (PC1-4 vs MAPD, mrpb, ontarget rate,total #reads)
all_cor <- cbind(cor_MAPD_targ,cor_MAPD_antitarg,cor_mrpb_targ,cor_mrpb_antitarg,cor_tot_reads,cor_ontarget_rate)
filename_cor_all <- "cor_all_PC1-4.jpeg"
jpeg(filename_cor_all,width=9,height=6,quality=90,units="in",res=600)
layout(matrix(1,1,1))
par(mar=c(9,4,3,1)+0.1)
barplot(all_cor,beside=TRUE,names.arg=c("MAPD targets","MAPD antitargets","mrpb targets","mrpb antitargets","total #reads","on-target rate"),las=2,ylab="Spearman correlation")
#legend(x=14,y=0.77,paste("PC",1:4,sep=""),fill=grey.colors(4))
legend("topleft",paste("PC",1:4,sep=""),fill=grey.colors(4))
dev.off()


#########################

#check cor between MAPD, mprb, ont-target rate and total #reads
plot(MAPD_antitargets_refFlat[,2],MAPD_targets_refFlat[,2],xaxt="n")
points(MAPD_antitargets_refFlat[-as.numeric(testset[,2]),2][clInd1],MAPD_targets_refFlat[-as.numeric(testset[,2]),2][clInd1],col="red")
points(MAPD_antitargets_refFlat[-as.numeric(testset[,2]),2][clInd2],MAPD_targets_refFlat[-as.numeric(testset[,2]),2][clInd2],col="green")
points(MAPD_antitargets_refFlat[-as.numeric(testset[,2]),2][clInd3],MAPD_targets_refFlat[-as.numeric(testset[,2]),2][clInd3],col="blue")
points(MAPD_antitargets_refFlat[-as.numeric(testset[,2]),2][clInd0],MAPD_targets_refFlat[-as.numeric(testset[,2]),2][clInd0],col="black")

plot(tot_reads[-as.integer(testset[,2]),1],mrpb_targets_refFlat[-as.integer(testset[,2]),2],xaxt="n")
points(tot_reads[-as.integer(testset[,2]),1][clInd1],mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),1][clInd2],mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),1][clInd3],mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),1][clInd0],mrpb_targets_refFlat[-as.integer(testset[,2]),2][clInd0],col="black")
cor(tot_reads[-as.integer(testset[,2]),1],as.numeric(mrpb_targets_refFlat[-as.integer(testset[,2]),2]))

plot(tot_reads[-as.integer(testset[,2]),2],mrpb_antitargets_refFlat[-as.integer(testset[,2]),2],xaxt="n")
points(tot_reads[-as.integer(testset[,2]),2][clInd1],mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),2][clInd2],mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),2][clInd3],mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),2][clInd0],mrpb_antitargets_refFlat[-as.integer(testset[,2]),2][clInd0],col="black")
cor(tot_reads[-as.integer(testset[,2]),2],as.numeric(mrpb_antitargets_refFlat[-as.integer(testset[,2]),2]))

#cor MAPD vs mrpb
cor(as.numeric(MAPD_antitargets_refFlat[,2]),as.numeric(mrpb_antitargets_refFlat[,2]),method="s")
cor(as.numeric(MAPD_targets_refFlat[,2]),as.numeric(mrpb_targets_refFlat[,2]),method="s")


#########################

#Check on-target rate for test samples and if clusters seem okay
layout(matrix(1:8,2,4,byrow=TRUE))
par(mar=c(4.5,4.4,3.7,1.8)+0.1)
plot(tot_reads[-as.integer(testset[,2]),1],x_inter[,1],type="n",xlab="total #reads",ylab="PC1",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_tot_reads[1],2)))
points(tot_reads[-as.integer(testset[,2]),1][clInd1],x_inter[,1][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),1][clInd2],x_inter[,1][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),1][clInd3],x_inter[,1][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),1][clInd0],x_inter[,1][clInd0],col="black")
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==1)],pc_test_all[,1][which(assign_clust_all==1)],col="red",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==2)],pc_test_all[,1][which(assign_clust_all==2)],col="green",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==3)],pc_test_all[,1][which(assign_clust_all==3)],col="blue",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==0)],pc_test_all[,1][which(assign_clust_all==0)],col="black",pch=8)
legend("topright",c("cluster 1","cluster 2","cluster 3","outliers"),col=c("red","green","blue","black"),pch=1)
plot(tot_reads[-as.integer(testset[,2]),1],x_inter[,2],type="n",xlab="total #reads",ylab="PC2",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_tot_reads[2],2)))
points(tot_reads[-as.integer(testset[,2]),1][clInd1],x_inter[,2][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),1][clInd2],x_inter[,2][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),1][clInd3],x_inter[,2][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),1][clInd0],x_inter[,2][clInd0],col="black")
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==1)],pc_test_all[,2][which(assign_clust_all==1)],col="red",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==2)],pc_test_all[,2][which(assign_clust_all==2)],col="green",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==3)],pc_test_all[,2][which(assign_clust_all==3)],col="blue",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==0)],pc_test_all[,2][which(assign_clust_all==0)],col="black",pch=8)
plot(tot_reads[-as.integer(testset[,2]),1],x_inter[,3],type="n",xlab="total #reads",ylab="PC3",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_tot_reads[3],2)))
points(tot_reads[-as.integer(testset[,2]),1][clInd1],x_inter[,3][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),1][clInd2],x_inter[,3][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),1][clInd3],x_inter[,3][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),1][clInd0],x_inter[,3][clInd0],col="black")
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==1)],pc_test_all[,3][which(assign_clust_all==1)],col="red",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==2)],pc_test_all[,3][which(assign_clust_all==2)],col="green",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==3)],pc_test_all[,3][which(assign_clust_all==3)],col="blue",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==0)],pc_test_all[,3][which(assign_clust_all==0)],col="black",pch=8)
plot(tot_reads[-as.integer(testset[,2]),1],x_inter[,4],type="n",xlab="total #reads",ylab="PC4",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_tot_reads[4],2)))
points(tot_reads[-as.integer(testset[,2]),1][clInd1],x_inter[,4][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),1][clInd2],x_inter[,4][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),1][clInd3],x_inter[,4][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),1][clInd0],x_inter[,4][clInd0],col="black")
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==1)],pc_test_all[,4][which(assign_clust_all==1)],col="red",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==2)],pc_test_all[,4][which(assign_clust_all==2)],col="green",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==3)],pc_test_all[,4][which(assign_clust_all==3)],col="blue",pch=8)
points(tot_reads[as.integer(testset[,2]),1][which(assign_clust_all==0)],pc_test_all[,4][which(assign_clust_all==0)],col="black",pch=8)
plot(tot_reads[-as.integer(testset[,2]),2],x_inter[,1],type="n",xlab="on-target rate",ylab="PC1",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_ontarget_rate[1],2)))
points(tot_reads[-as.integer(testset[,2]),2][clInd1],x_inter[,1][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),2][clInd2],x_inter[,1][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),2][clInd3],x_inter[,1][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),2][clInd0],x_inter[,1][clInd0],col="black")
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==1)],pc_test_all[,1][which(assign_clust_all==1)],col="red",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==2)],pc_test_all[,1][which(assign_clust_all==2)],col="green",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==3)],pc_test_all[,1][which(assign_clust_all==3)],col="blue",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==0)],pc_test_all[,1][which(assign_clust_all==0)],col="black",pch=8)
plot(tot_reads[-as.integer(testset[,2]),2],x_inter[,2],type="n",xlab="on-target rate",ylab="PC2",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_ontarget_rate[2],2)))
points(tot_reads[-as.integer(testset[,2]),2][clInd1],x_inter[,2][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),2][clInd2],x_inter[,2][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),2][clInd3],x_inter[,2][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),2][clInd0],x_inter[,2][clInd0],col="black")
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==1)],pc_test_all[,2][which(assign_clust_all==1)],col="red",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==2)],pc_test_all[,2][which(assign_clust_all==2)],col="green",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==3)],pc_test_all[,2][which(assign_clust_all==3)],col="blue",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==0)],pc_test_all[,2][which(assign_clust_all==0)],col="black",pch=8)
plot(tot_reads[-as.integer(testset[,2]),2],x_inter[,3],type="n",xlab="on-target rate",ylab="PC3",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_ontarget_rate[3],2)))
points(tot_reads[-as.integer(testset[,2]),2][clInd1],x_inter[,3][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),2][clInd2],x_inter[,3][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),2][clInd3],x_inter[,3][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),2][clInd0],x_inter[,3][clInd0],col="black")
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==1)],pc_test_all[,3][which(assign_clust_all==1)],col="red",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==2)],pc_test_all[,3][which(assign_clust_all==2)],col="green",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==3)],pc_test_all[,3][which(assign_clust_all==3)],col="blue",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==0)],pc_test_all[,3][which(assign_clust_all==0)],col="black",pch=8)
plot(tot_reads[-as.integer(testset[,2]),2],x_inter[,4],type="n",xlab="on-target rate",ylab="PC4",cex.lab=1.5,cex.axis=1.5,main=paste("correlation =",signif(cor_ontarget_rate[4],2)))
points(tot_reads[-as.integer(testset[,2]),2][clInd1],x_inter[,4][clInd1],col="red")
points(tot_reads[-as.integer(testset[,2]),2][clInd2],x_inter[,4][clInd2],col="green")
points(tot_reads[-as.integer(testset[,2]),2][clInd3],x_inter[,4][clInd3],col="blue")
points(tot_reads[-as.integer(testset[,2]),2][clInd0],x_inter[,4][clInd0],col="black")
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==1)],pc_test_all[,4][which(assign_clust_all==1)],col="red",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==2)],pc_test_all[,4][which(assign_clust_all==2)],col="green",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==3)],pc_test_all[,4][which(assign_clust_all==3)],col="blue",pch=8)
points(tot_reads[as.integer(testset[,2]),2][which(assign_clust_all==0)],pc_test_all[,4][which(assign_clust_all==0)],col="black",pch=8)


##################################

#check distributions of coeffs in fitted functions
layout(matrix(1:6,2,3,byrow=TRUE))
hist(coeff_fit[1,],xlim=c(-1,1),breaks=50)
hist(coeff_fit[2,],xlim=c(-1,1),breaks=50)
hist(coeff_fit[3,],xlim=c(-1,1),breaks=50)
hist(coeff_fit[4,],xlim=c(-1,1),breaks=50)
hist(coeff_fit[5,],xlim=c(-1,1),breaks=50)


